
#include-once

Func Script()
	Local $this = _AutoItObject_Class()
	
	$this.Create()
	
	
	
	Return $this.Object
EndFunc

; brought over from GUIBuilderNXT for future integration

#Region ; code generation
;~ Func _code_generation()
;~     Local $_controls

;~     ; Mod by: TheSaint
;~     Local $includes = "#include <Constants.au3>"        & @CRLF & _
;~                       "#include <GUIConstantsEx.au3>"   & @CRLF & _                      
;~                       "#include <Misc.au3>"             & @CRLF & _
;~                       "#include <WindowsConstants.au3>"

;~     Local Const $ctrl_count = $mControls.ControlCount

;~     For $i = 1 To $ctrl_count
;~         $_controls &= _generate_controls($i)

;~         $includes &= _generate_includes($i, $includes)
;~     Next

;~     Local Const $w = $win_client_size[0]

;~     Local Const $h = $win_client_size[1]

;~     ; Mod by TheSaint
;~     Local Const $code = "#Region ; GUI generated by " & _program_name() & " " & _program_version()                                & @CRLF & @CRLF &               _
;~             $includes                                                                                                             & @CRLF & @CRLF &               _
;~             "Global $MainStyle = BitOR($WS_OVERLAPPED, $WS_CAPTION, $WS_SYSMENU, $WS_VISIBLE, $WS_CLIPSIBLINGS, $WS_MINIMIZEBOX)" & @CRLF & @CRLF &               _
;~             "Global $hMain = GuiCreate(" & $gdtitle & ", " & $w & ", " & $h & ", -1, -1, $MainStyle)"                             & @CRLF & @CRLF &               _
;~             $_controls                                                                                                            & @CRLF &                       _
;~             "GuiSetState(@SW_SHOWNORMAL)"                                                                                         & @CRLF & @CRLF &               _
;~             "Do"                                                                                                                  & @CRLF & @TAB  &               _
;~             "Switch GuiGetMsg()"                                                                                                  & @CRLF & @TAB  & @TAB &        _
;~             "Case $GUI_EVENT_CLOSE"                                                                                               & @CRLF & @TAB  & @TAB & @TAB & _
;~             "ExitLoop"                                                                                                            & @CRLF & @CRLF & @TAB & @TAB & _
;~             "Case Else"                                                                                                           & @CRLF & @TAB  & @TAB & @TAB & _
;~             ";"                                                                                                                   & @CRLF & @TAB  &               _
;~             "EndSwitch"                                                                                                           & @CRLF &                       _
;~             "Until False"                                                                                                         & @CRLF &                       _
;~ 			"#EndRegion"

;~     _copy_code_to_output($code)
;~ EndFunc

;~ Func _generate_controls(Const $i)
;~     Local Const $mCtrl = $mControls[$i]

;~     Local Const $ltwh = $mCtrl.Left & ", " & $mCtrl.Top & ", " & $mCtrl.Width & ", " & $mCtrl.Height

;~     ; The general template is GUICtrlCreateXXX( "text", left, top [, width [, height [, style [, exStyle]]] )
;~     ; but some controls do not use this.... Avi, Icon, Menu, Menuitem, Progress, Tabitem, Treeviewitem, updown
;~     Local $mControls

;~     Switch StringStripWS($mCtrl.Name, $STR_STRIPALL) <> ''
;~         Case True
;~             $mControls = "Global $" & $mCtrl.Type & '_' & $i & " = "
;~     EndSwitch  

;~     Switch $mCtrl.Type
;~         Case "Progress", "Slider", "TreeView" ; no text field
;~             $mControls &= "GuiCtrlCreate" & $mCtrl.Type & '(' & $ltwh & ")" & @CRLF

;~         Case "Icon" ; extra iconid [set to zero]
;~             $mControls &= "GuiCtrlCreate" & $mCtrl.Type & '("' & $mCtrl.Text & '", 0, ' & $ltwh & ")" & @CRLF
;~ 						
;~         Case "Tab"
;~             $mControls &= "GuiCtrlCreate" & $mCtrl.Type & '(' & $ltwh & ')' & @CRLF & @CRLF
;~             
;~             $mControls &= "_GUICtrlTab_InsertItem($" & $mCtrl.Type & '_' & $i & ", 0, ""Tab1"")" & @CRLF
;~             
;~         Case Else
;~             $mControls &= "GuiCtrlCreate" & $mCtrl.Type & '("' & $mCtrl.Text & '", ' & $ltwh & ")" & @CRLF
;~     EndSwitch

;~     Return $mControls
;~ EndFunc

;~ Func _generate_includes(Const $i, Const $includes)
;~     Local Const $mCtrl = $mControls[$i]

;~     Switch $mCtrl.Type
;~         Case "Button", "Checkbox", "Group", "Radio"
;~             If Not StringInStr($includes, "<ButtonConstants.au3>") Then
;~                 Return @CRLF & "#include <ButtonConstants.au3>"
;~             EndIf
;~             
;~         Case "Tab"
;~             If Not StringInStr($includes, "<GUITab.au3>") Then
;~                 Return @CRLF & "#include <GUITab.au3>"
;~             EndIf

;~         Case "Date"
;~             If Not StringInStr($includes, "<DateTimeConstants.au3>") Then
;~                 Return @CRLF & "#include <DateTimeConstants.au3>"
;~             EndIf

;~         Case "Edit", "Input"
;~             If Not StringInStr($includes, "<EditConstants.au3>") Then
;~                 Return @CRLF & "#include <EditConstants.au3>"
;~             EndIf

;~         Case "Icon", "Label", "Pic"
;~             If Not StringInStr($includes, "<StaticConstants.au3>") Then
;~                 Return @CRLF & "#include <StaticConstants.au3>"
;~             EndIf

;~         Case "List"
;~             If Not StringInStr($includes, "<ListBoxConstants.au3>") Then
;~                 Return @CRLF & "#include <ListBoxConstants.au3>"
;~             EndIf

;~         Case "Progress", "Slider", "TreeView", "Combo"
;~             If Not StringInStr($includes, '<' & $mCtrl.Type & "Constants.au3>") Then
;~                 Return @CRLF & "#include <" & $mCtrl.Type & "Constants.au3>"
;~             EndIf
;~     EndSwitch

;~     Return ""
;~ EndFunc

;~ Func _copy_code_to_output(Const $code)
;~     ; mod by: TheSaint
;~     Switch StringInStr($CmdLineRaw, "/StdOut")
;~         Case True
;~             ConsoleWrite("#region ; --- " & _program_name() & " generated code Start ---"  & @CRLF & _
;~                     StringReplace($code, @CRLF, @LF)                                & @CRLF & _
;~                     "#endregion ; --- " & _program_name() & " generated code End ---" & @CRLF)

;~         Case False
;~             If $mygui = "" Then
;~                 $mygui = "MyGUI.au3"
;~             EndIf

;~             Local Const $destination = FileSaveDialog("Save GUI to file?", "", "AutoIt (*.au3)", BitOR($FD_FILEMUSTEXIST, $FD_PATHMUSTEXIST, $FD_PROMPTOVERWRITE), $mygui)

;~             If @error = 1 Or Not $destination Then
;~                 ClipPut($code)

;~                 SplashTextOn("Done", @CRLF & "Script copied to clipboard!", 200, 100)
;~             Else
;~                 FileDelete($destination)

;~                 FileWrite($destination, $code)

;~                 SplashTextOn("Done", @CRLF & "Saved to file!", 200, 100)
;~             EndIf

;~             Sleep(1000)

;~             SplashOff()
;~     EndSwitch
;~     ; END of modification by TheSaint
;~ EndFunc
#EndRegion